CREATE TABLE School
(name VARCHAR(256) NOT NULL PRIMARY KEY,
 size INTEGER NOT NULL,
 rank INTEGER NOT NULL,
 tuition INTEGER NOT NULL
);

CREATE TABLE University
(name VARCHAR(256) NOT NULL REFERENCES School(name)
);

CREATE TABLE College
(name VARCHAR(256) NOT NULL REFERENCES School(name),
 highest_degree VARCHAR(256) NOT NULL
);

CREATE TABLE City
(name VARCHAR(256) NOT NULL,
 state VARCHAR(256) NOT NULL,
population INTEGER NOT NULL,
cost INTEGER NOT NULL,
crime INTEGER NOT NULL,
PRIMARY KEY (name, state)
);

CREATE TABLE Location
(school_name VARCHAR(256) NOT NULL REFERENCES School(name),
 city_name VARCHAR(256) NOT NULL,
 state VARCHAR(256) NOT NULL
);

CREATE TABLE Program
(name VARCHAR(256) NOT NULL PRIMARY KEY,
 category VARCHAR(256) NOT NULL UNIQUE,
 expected_salary INTEGER NOT NULL
);

CREATE TABLE Offering
(school_name VARCHAR(256) NOT NULL REFERENCES School(name),
 program_name VARCHAR(256) NOT NULL REFERENCES Program(name)
);
